### ISSUE TITLE
没有下载速度

### ISSUE THREAD

**Issue by dydhyhwu** [AmbitiousJun/video-downloader-go#1]
![image](https://github.com/AmbitiousJun/video-downloader-go/assets/7239380/e519c88a-4d42-4b65-be3f-0b98ca3bb193)
下载感觉完全没速度， 有啥办法么

**Comment by AmbitiousJun** [comment]
你是通过什么方式下呢，YouTube-dl解析出来的吗，什么网站

**Comment by dydhyhwu** [comment]
> 你是通过什么方式下呢，YouTube-dl解析出来的吗，什么网站

yt-dlp， 重命名了一下。 腾讯视频的，斗罗大陆合集

**Comment by AmbitiousJun** [comment]
> > 你是通过什么方式下呢，YouTube-dl解析出来的吗，什么网站
> 
> yt-dlp， 重命名了一下。 腾讯视频的，斗罗大陆合集

腾讯视频确实会这样，两三个月前 yt-dlp 就下不动腾讯视频了，我有去提 issue，但是它们没修复

**Comment by AmbitiousJun** [comment]
> > 你是通过什么方式下呢，YouTube-dl解析出来的吗，什么网站
> 
> yt-dlp， 重命名了一下。 腾讯视频的，斗罗大陆合集

我现在个人的解决方案就是浏览器添加个猫抓扩展, 通过猫抓手动抓取 m3u8 下载地址，这个是下得动的，yt-dlp 解析出来的就不行

**Comment by dydhyhwu** [comment]
> > > 你是通过什么方式下呢，YouTube-dl解析出来的吗，什么网站
> > 
> > 
> > yt-dlp， 重命名了一下。 腾讯视频的，斗罗大陆合集
> 
> 我现在个人的解决方案就是浏览器添加个猫抓扩展, 通过猫抓手动抓取 m3u8 下载地址，这个是下得动的，yt-dlp 解析出来的就不行

抓到的是单个还是多个呀？那解析器你用啥，我想用你这个项目直接能够下下来就好了

**Comment by AmbitiousJun** [comment]
> > > > 你是通过什么方式下呢，YouTube-dl解析出来的吗，什么网站
> > > 
> > > 
> > > yt-dlp， 重命名了一下。 腾讯视频的，斗罗大陆合集
> > 
> > 
> > 我现在个人的解决方案就是浏览器添加个猫抓扩展, 通过猫抓手动抓取 m3u8 下载地址，这个是下得动的，yt-dlp 解析出来的就不行
> 
> 抓到的是单个还是多个呀？那解析器你用啥，我想用你这个项目直接能够下下来就好了

现在 yt-dlp 用来下载芒果和b站是没问题的，腾讯视频用猫抓只能单个单个抓了，其实借助一些剪贴板工具手动抓全集m3u8也不会太麻烦，我用的是utools剪贴板

**Comment by dydhyhwu** [comment]
> > > > > 你是通过什么方式下呢，YouTube-dl解析出来的吗，什么网站
> > > > 
> > > > 
> > > > yt-dlp， 重命名了一下。 腾讯视频的，斗罗大陆合集
> > > 
> > > 
> > > 我现在个人的解决方案就是浏览器添加个猫抓扩展, 通过猫抓手动抓取 m3u8 下载地址，这个是下得动的，yt-dlp 解析出来的就不行
> > 
> > 
> > 抓到的是单个还是多个呀？那解析器你用啥，我想用你这个项目直接能够下下来就好了
> 
> 现在 yt-dlp 用来下载芒果和b站是没问题的，腾讯视频用猫抓只能单个单个抓了，其实借助一些剪贴板工具手动抓全集m3u8也不会太麻烦，我用的是utools剪贴板

了解， thanks， 晚上我试试。 爱奇艺和优酷也可以么？

**Comment by AmbitiousJun** [comment]
> > > > > > 你是通过什么方式下呢，YouTube-dl解析出来的吗，什么网站
> > > > > 
> > > > > 
> > > > > yt-dlp， 重命名了一下。 腾讯视频的，斗罗大陆合集
> > > > 
> > > > 
> > > > 我现在个人的解决方案就是浏览器添加个猫抓扩展, 通过猫抓手动抓取 m3u8 下载地址，这个是下得动的，yt-dlp 解析出来的就不行
> > > 
> > > 
> > > 抓到的是单个还是多个呀？那解析器你用啥，我想用你这个项目直接能够下下来就好了
> > 
> > 
> > 现在 yt-dlp 用来下载芒果和b站是没问题的，腾讯视频用猫抓只能单个单个抓了，其实借助一些剪贴板工具手动抓全集m3u8也不会太麻烦，我用的是utools剪贴板
> 
> 了解， thanks， 晚上我试试。 爱奇艺和优酷也可以么？

爱奇艺应该没问题，优酷的话有些不行，只能下载没加密的，加密视频得其他手段

**Comment by dydhyhwu** [comment]
好滴， 谢谢～ 希望项目能越来越棒
